
export const NEWS_CATEGORIES = {
    BASE: [
        "Winnie says: 'This is fine.' 🔥",
        "Winnie asks: 'Have you tried eating more Cheetos?'",
        "Winnie declares 'Treats are deductible' in new policy update.",
        "Winnie: 'Compliance is just a suggestion.'",
        "Winnie suggests paying claims with belly rubs.",
        "Winnie napping on important merger documents.",
        "Winnie: 'I don't get out of bed for less than 1 million treats.'",
        "Winnie barking at invisible auditors.",
        "Winnie refuses to wear a tie to the board meeting.",
        "Winnie demands a seat at the head of the table.",
        "Winnie: 'Who's a good CEO? I am.'",
        "Winnie caught chasing her tail during press conference.",
        "Winnie: 'My strategy is simple: Eat first, deny claims later.'",
        "Winnie: 'Paws off my profits.'",
        "Winnie: 'I smell revenue... and bacon.'",
        "Winnie: 'Why is the graph red? Make it green or I bite.'",
        "Winnie howl-singing the company anthem.",
        "Winnie: 'Meetings could be emails. Emails could be snacks.'",
        "Winnie judging the stock price. It went up.",
        "Winnie: 'Human resources? You mean treat dispensers.'",
        "Winnie: 'Synergy is just a fancy word for pack hunting.'",
        "Winnie bites the hand that feeds (the auditors).",
        "Winnie: 'I'm not sleeping, I'm meditating on profit.'",
        "Winnie: 'The laser pointer is a metaphor for market share.'",
        "Winnie violently shaking a stuffed bear named 'Regulation'.",
        "Winnie: 'No take, only throw. No refund, only premium.'",
        "Winnie creates new department: Department of Nap.",
        "Winnie: 'Walkies? No. Stonkies.'",
        "Winnie: 'I am the goodest girl with the baddest margins.'",
        "Winnie: 'Belly rubs are mandatory. Raises are optional.'",
        "Winnie zooming through the office at 3 AM.",
        "Winnie: 'I heard a wrapper. Is that a claim or a snack?'",
        "Winnie: 'My fur is worth more than your car.'",
        "Winnie: 'I don't beg. I negotiate.'",
        "Winnie: 'The vacuum cleaner is the enemy of capitalism.'",
        "Winnie chewing on a pen. It was a Montblanc.",
        "Winnie: 'I did not eat the quarterly report. It was a glitch.'",
        "Winnie: 'Squirrels are just unpaid interns.'",
        "Winnie: 'I need a vacation. And by vacation, I mean your chair.'",
        "Winnie: 'Rub my ears and tell me I'm rich.'",
        "Winnie: 'The mailman is a government spy.'",
        "Winnie: 'I don't have fleas, I have dividends.'",
        "Winnie: 'Bark softly and carry a big cheeto.'",
        "Winnie: 'I'm not stubborn, I'm market-resilient.'",
        "Winnie: 'Loyalty is bought with cheese.'",
        "Winnie: 'I'm cute, therefore I am exempt from taxes.'",
        "Winnie: 'Don't look at me like that, I know what I did.'",
        "Winnie: 'It's not a bug, it's a feature. Now feed me.'",
        "Winnie: 'I accept payments in crypto-kibble.'",
        "Winnie: 'The glass ceiling is made of treats.'",
        "Moppet (the cat) officially appointed as COO (Chief Overlooking Officer).",
        "Breaking: Winnie caught using Daisy (the kitten) as 'adorable bait' for a pepperoni heist.",
        "Moppet judges Winnie's quarterly report: 'Needs more fish, less barking.'",
        "Daisy the kitten files for emancipation after Winnie sits on her for the third time today.",
        "Winnie seen leading a specialized tactical unit consisting of one grumpy cat and one confused kitten.",
        "Moppet: 'I don't care about the revenue, just keep the dog away from my sunbeam.'",
        "Daisy caught practicing hissing in the mirror. Winnie: 'She's a natural at middle management.'",
        "Winnie blames the empty Cheeto bag on a 'mysterious feline intruder' named Moppet.",
        "Moppet denies involvement in the Great Bag Ripping of 4 PM: 'I have an alibi, I was napping.'",
        "Daisy attempting to climb Winnie to reach the 'Forbidden Counter Treats'.",
        "Winnie: 'Moppet handles the technicals, Daisy handles the 'eyes', and I handle the snacks.'",
        "Daisy found sleeping in the CEO's bed. Winnie: 'This is a hostile takeover.'",
        "Moppet: 'Winnie's leadership style is best described as... moist.'",
        "Daisy: 'When I grow up, I want to have as much audacity as Winnie.'",
        "Breaking: Winnie caught head-first in a Flamin' Hot Cheeto bag. Claims she was 'inspecting the seal'.",
        "Winnie: 'I didn't steal the Cheetos, they were clearly seeking political asylum in my mouth.'",
        "Alert: Winnie has successfully stickied your favorite bag with orange paw prints.",
        "Winnie: 'Why is there a zipper on this snack bag? It's like you're trying to hide the truth from me.'",
        "Scandal: Winnie caught using 'Stealth Mode' (just crawling slowly) to reach your Cheeto stash.",
        "Winnie: 'I don't have orange fur, that's just a light reflection from the Cheeto bag I definitely didn't open.'",
        "Alert: Your backpack has been designated as a 'Free Treat Zone' by CEO Winnie.",
        "Winnie: 'If you didn't want the Cheetos eaten, why are they Cheeto-shaped? Checkmate, human.'",
        "Winnie caught licking the inside of a 'cleaned' Cheeto bag for 45 minutes straight.",
        "Winnie: 'I'm not stealing, I'm just performing a mandatory quality control check on your backpack.'",
        "Winnie demands a bigger office. And by office, she means the couch.",
        "Moppet seen pushing Winnie's coffee off the desk. 'Market volatility,' she explains.",
        "Daisy successfully hunted a dust bunny. She is now the Head of Security.",
        "Winnie's morning routine: Wake up, bark at nothing, profit.",
        "Moppet refuses to sign the merger. It didn't have enough tuna.",
        "Winnie: 'I'm not fat, I'm bloated with success... and Cheetos.'",
        "Daisy learning the corporate ladder. She's currently on the second step of the stairs.",
        "Winnie: 'Bork once for yes, twice for more treats.'",
        "Moppet: 'I'm not lazy, I'm a strategic asset in standby mode.'",
        "Daisy: 'Why is the dog so loud? Is barking a taxable event?'",
        "Winnie: 'I've outsourced the cat chasing to a Roomba. Results are mixed.'",
        "Moppet caught editing the bylaws to include mandatory 20-hour nap days.",
        "Winnie: 'I'm a self-made dog. I started with nothing but a dream and a stolen cheeto.'",
        "Daisy: 'If I fit, I sit. Even if it's the ledger.'",
        "Winnie seen trying to pay the electric bill with a half-chewed tennis ball.",
        "Moppet: 'Profit margins? I prefer salmon portions.'",
        "Daisy: 'Everything is a toy if you try hard enough. Including the CEO's tail.'",
        "Winnie: 'I don't need a gym. Chasing the mailman is my cardio.'",
        "Moppet: 'The vacuum is the only auditor I fear.'",
        "Daisy: 'Is 'psst psst psst' a legally binding contract internal to the company?'"
    ],
    SCANDAL: [
        "Breaking: Winnie arrested for DUI while operating a Red Little Tikes Cozy Coupe.",
        "Winnie seen fleeing the scene of a tipped-over trash can in her plastic car.",
        "Winnie: 'I thought the juice box was non-alcoholic!'",
        "Police Report: CEO Winnie resisting arrest by showing her 'good girl' license.",
        "Scandal: Winnie caught funneling treat funds into a high-stakes squirrel-watching ring.",
        "Winnie under investigation for tax evasion. 'I paid in bones,' she claims.",
        "Illegal: Winnie installs unauthorized hot cheeto dispenser in city hall.",
        "Winnie caught bribing health inspectors with slightly licked crackers.",
        "Breaking: Winnie's insurance empire accused of money laundering via laundromat squeaky toys.",
        "Winnie on the run! Last seen doing 3mph in a Little Tikes car near the border.",
        "Scandal: Secret recordings reveal Winnie thinks cats are 'okay-ish'. Stock drops 40%.",
        "Winnie impersonating a police paw-fficer to steal pepperoni.",
        "Security footage shows Winnie 'borrowing' the neighbor's garden hose for a pool party.",
        "Winnie's legal team: 'She's too cute to stand trial.' Jury agrees.",
        "Scandal: Winnie's Little Tikes car found with expired registration sticker (a dinosaur sticker).",
        "Winnie caught smuggling contraband kibble inside a hollowed-out tennis ball.",
        "Breaking: Winnie denies involvement in the 'Great Shoe Chewing' of 2025.",
        "Winnie: 'The handcuffs are basically just a very uncomfortable leash.'",
        "Winnie's prison sentence reduced to 5 minutes of 'time-out'. She escaped in 2.",
        "Scandal: Winnie caught using company drones to drop Cheetos on her rivals.",
        "Breaking: Winnie's Little Tikes car impounded for 'reckless tail wagging'.",
        "Winnie accused of running a Ponzi scheme. 'It's a Paws-zi scheme!' she yells.",
        "Scandal: Secret documents show Winnie hasn't actually been a 'good girl' since Tuesday.",
        "Legal: Winnie's 'Right to Zoom' lawsuit reaches the Supreme Court.",
        "Breaking: Winnie caught operating an unlicensed 'Belly Rub' stand without a permit.",
        "Winnie's legal fees now exceed the GDP of some small snack-based nations.",
        "Scandal: Winnie caught using insider info to buy the 'Last Bag of Flamin' Hots'.",
        "Winnie seen wearing a disguise (a fake mustache) to evade the auditors.",
        "Breaking: Winnie's insurance policy for 'Acts of Moppet' found to be a total scam.",
        "Scandal: Winnie caught 'polishing' the company books with her tongue.",
        "Breaking: Winnie arrested for stealing the moon. 'It looked like a giant wheel of cheese!'",
        "Justice: Winnie's 'Little Tikes' car has been booted. She just chewed the boot off.",
        "Scandal: Winnie accused of 'treat-washing' illegal gains through a kitten orphanage.",
        "Winnie: 'I didn't flee the country, I was just doing a very long zoomie across the border.'"
    ],
    INSURANCE_SATIRE: [
        "Breaking: Local cat denied coverage due to 'pre-existing attitude'.",
        "Coverage denied: 'Patient failed to wiggle tail sufficiently.'",
        "New Policy: 'Walks are considered elective surgery.'",
        "Claim rejected: 'Squeaky toy usage exceeded annual limit.'",
        "Premiums rise 200% because 'Why not?'.",
        "Customer Service hold music is just Winnie barking.",
        "Prior Authorization required for breathing air.",
        "Deductible now payable in soul fragments.",
        "Out-of-Network provider? That's a paddling.",
        "Coverage gap? Just jump over it.",
        "Wellness check result: You are too poor to be sick.",
        "Policy update: 'Acts of God' now include 'Acts of Dog'.",
        "Co-pay for emergency room visit: Your firstborn.",
        "Pharmacy benefit manager is a raccoon in a dumpster.",
        "New plan option: 'The Placebo Plus'.",
        "Claim denied: 'Legalese was too understandable.'",
        "Emergency room wait times now measured in 'Dog Years'.",
        "Doctor note required for being sad.",
        "Pre-approval needed for sneezing.",
        "Vision benefits cover one eye only.",
        "Dental plan covers chewing on sticks.",
        "Mental health coverage replaced with 'Get over it'.",
        "Maternity leave? Only for puppies.",
        "Physical therapy is just chasing a ball.",
        "Prescription coverage tier 1: Tic Tacs.",
        "Prescription coverage tier 4: Unobtainium.",
        "Hospital bill itemized: $500 for 'Emotional Damage'.",
        "Ambulance ride now requires Uber surge pricing.",
        "Preventative care is now 'Post-ventative'.",
        "Telehealth visit is just a Zoom call with a plushie.",
        "Explanation of Benefits: 'We pay nothing, you pay everything.'",
        "Lifetime maximum reached at age 3.",
        "Network directory last updated: 1994.",
        "Referral needed to see your own reflection.",
        "HSA funds used to buy yacht for CEO.",
        "FSA funds expire in 5 minutes.",
        "Open Enrollment is closed. Forever.",
        "Qualifying Life Event: Becoming a Shiba Inu.",
        "Claim processing time: 6-8 business decades.",
        "Appeals process involves a trial by combat.",
        "Customer satisfaction survey is a trap.",
        "Member ID card is printed on sandpaper.",
        "Provider network includes 0 doctors and 1 vet.",
        "Coverage for 'Belly Aches' excludes 'Too Many Treats'.",
        "Pre-existing condition: Being alive.",
        "Genetic testing reveals you are 100% liable.",
        "Wellness program is just a poster that says 'Live'.",
        "Smoking cessation program: Stop it.",
        "Weight loss program: Eat less, bark more.",
        "Stress management: Scream into the void.",
        "Policy update: 'Being a cat' is now a terminable offense.",
        "New co-pay: One lick of your ice cream cone.",
        "Coverage denied: 'Patient's bark was louder than 80 decibels.'",
        "Insurance ID cards now double as coasters. 'Efficiency!' says CEO.",
        "New claim type: 'Emotional distress caused by the vacuum cleaner.'",
        "Deductible resets every time the mailman visits.",
        "Emergency room snack machine now counts as 'In-Network'."
    ],
    CHAOS: [
        "Winnie: 'Is the room spinning or is it just me?' 🌀",
        "Audit warning: 'Hide the treats!'",
        "Meltdown imminent: 'Too spicy! Too spicy!'",
        "Winnie: 'Gravity is optional today.'",
        "Chaos Index rising: 'Who put the cat in charge?'",
        "Winnie: 'I AM THE SENATE.' 👑",
        "Winnie: 'This is not a meltdown, it's a flavor explosion.'",
        "Winnie: 'The auditors are coming! Act normal!'",
        "Winnie: 'Normal is boring. Be chaotic.'",
        "Winnie: 'I pressed the red button. It looked like a berry.'",
        "Winnie: 'Why is the ceiling on the floor?'",
        "Winnie: 'Physics checking out. Bye.'",
        "Winnie: 'Time is a flat circle. Like a frisbee.'",
        "Winnie: 'The numbers are dancing. I like it.'",
        "Winnie: 'Reality is trembling. Needs more salt.'",
        "Winnie: 'Who turned off the laws of thermodynamics?'",
        "Winnie: 'Entropy is my middle name.'",
        "Winnie: 'Order is for cats.'",
        "Winnie: 'Let the galaxy burn. I have insurance.'",
        "Winnie: 'I accidentally insured the apocalypse.'",
        "Winnie: 'The void staring back. Asking for coverage.'",
        "Winnie: 'Dimensional rift opened in break room.'",
        "Winnie: 'Aliens denied coverage. Out of network.'",
        "Winnie: 'Time travel not covered. Pre-existing condition.'",
        "Winnie: 'Black holes are not a valid address.'",
        "Winnie: 'Parallel universe Winnie is richer.'",
        "Winnie: 'Schrödinger's cat is denied. Dead or alive?'",
        "Winnie: 'E=mc^2 is just a suggestion.'",
        "Winnie: 'Gravity requires prior authorization.'",
        "Winnie: 'Speed of light exceeded. Premium increased.'",
        "Winnie: 'Teleportation accident? Not covered.'",
        "Winnie: 'Zombie virus outbreak? Copay is brains.'",
        "Winnie: 'Robot uprising? We insured the robots.'",
        "Winnie: 'Simulation glitch. Rebooting revenue.'",
        "Winnie: 'The matrix runs on Windows 95.'",
        "Winnie: 'I am the glitch.'",
        "Winnie: 'Error 404: Ethics not found.'",
        "Winnie: 'Blue screen of death is pretty.'",
        "Winnie: 'Ctrl+Alt+Delete the competition.'",
        "Winnie: 'I hacked the mainframe. It had snacks.'",
        "Winnie: 'Cyber-security is just barking at the router.'",
        "Winnie: 'Phishing email? I ate the fish.'",
        "Winnie: 'Cloud storage? I prefer cloud napping.'",
        "Winnie: 'Blockchain? Is that a new leash?'",
        "Winnie: 'Crypto? I prefer Crypt-Keeper.'",
        "Winnie: 'NFT: Nice Fluffy Tail.'",
        "Winnie: 'My password is password123. Hack me.'",
        "Winnie: 'Firewall? I peed on it.'",
        "Winnie: 'Virus definition updated: Cuteness.'",
        "Breaking: Local gravity has been denied for 'excessive floating'.",
        "Winnie: 'I accidentally divided by zero. It tasted like chicken.'",
        "Alert: Your reality will expire in 24 hours unless a premium is paid.",
        "Winnie: 'I'm not a dog, I'm a decentralized autonomous organism.'",
        "Glitched: The CEO's tail is now a 404 error.",
        "Winnie: 'If you see an auditor from another dimension, don't feed them.'",
        "Breaking: Time has been paused to allow for a corporate-wide nap.",
        "Winnie: 'I insured my own existence. Now I'm literally too big to fail.'"
    ]
};

// Procedural generators will now return arrays so they can be merged per state
export const NEWS_GENERATORS = {
    CRIMES: () => {
        const msgs = [];
        const crimes = ['insider trading', 'fraud', 'treat smuggling', 'unlicensed zoomies', 'illegal barking', 'grand theft squeaky', 'bribery', 'tax evasion', 'public napping', 'counterfeit bones'];
        const punishments = ['5 minutes of time-out', 'no treats for an hour', 'mandatory bath', 'wearing a cone', 'social media apology', 'community service (tail wagging)', 'a stern talking-to', 'forfeit of the favorite toy', 'exile to the crate', 'loss of couch privileges'];
        crimes.forEach(crime => {
            punishments.forEach(punish => {
                msgs.push(`Justice: Winnie found guilty of ${crime}. Sentence: ${punish}.`);
            });
        });
        return msgs;
    },
    THEFT: () => {
        const msgs = [];
        const objects = ['Little Tikes car', 'squeaky duck', "neighbor's cat", "the mailman's bag", 'a giant cheeto', 'the CEO chair', 'the company vault', 'a delivery truck', 'the internet', 'gravity'];
        const theftActions = ['stole', 'hijacked', 'liquidated', 'chewed on', 'buried', 'repossessed', 'indexed', 'sold on the dark web', 'ate', 'lost'];
        objects.forEach(obj => {
            theftActions.forEach(act => {
                msgs.push(`Alert: Winnie ${act} ${obj} during an illegal spree.`);
            });
        });
        return msgs;
    },
    SIBLINGS: () => {
        const msgs = [];
        const sibs = ['Moppet', 'Daisy'];
        const sibActions = ['judges', 'ignores', 'hisses at', 'naps on', 'steals from', 'outsmarts', 'judiciously bats at', 'critiques', 'demotes', 'hides from'];
        const results = ['the quarterly earnings', "Winnie's strategy", 'the treat stash', 'the CEO chair', 'the entire board of directors', 'the latest scandal', "Winnie's Little Tikes car", 'the Cheeto pile', 'the insurance policy', 'the morning zoomies'];
        sibs.forEach(sib => {
            sibActions.forEach(act => {
                results.forEach(res => {
                    msgs.push(`Family Drama: ${sib} ${act} ${res}.`);
                });
            });
        });
        return msgs;
    }
};
