
export const NEWS_CATEGORIES = {
    BASE: [
        "Winnie says: 'This is fine.' 🔥",
        "Winnie asks: 'Have you tried eating more Cheetos?'",
        "Winnie declares 'Treats are deductible' in new policy update.",
        "Winnie: 'Compliance is just a suggestion.'",
        "Winnie suggests paying claims with belly rubs.",
        "Winnie napping on important merger documents.",
        "Winnie: 'I don't get out of bed for less than 1 million treats.'",
        "Winnie barking at invisible auditors.",
        "Winnie refuses to wear a tie to the board meeting.",
        "Winnie demands a seat at the head of the table.",
        "Winnie: 'Who's a good CEO? I am.'",
        "Winnie caught chasing her tail during press conference.",
        "Winnie: 'My strategy is simple: Eat first, deny claims later.'",
        "Winnie: 'Paws off my profits.'",
        "Winnie: 'I smell revenue... and bacon.'",
        "Winnie: 'Why is the graph red? Make it green or I bite.'",
        "Winnie howl-singing the company anthem.",
        "Winnie: 'Meetings could be emails. Emails could be snacks.'",
        "Winnie judging the stock price. It went up.",
        "Winnie: 'Human resources? You mean treat dispensers.'",
        "Winnie: 'Synergy is just a fancy word for pack hunting.'",
        "Winnie bites the hand that feeds (the auditors).",
        "Winnie: 'I'm not sleeping, I'm meditating on profit.'",
        "Winnie: 'The laser pointer is a metaphor for market share.'",
        "Winnie violently shaking a stuffed bear named 'Regulation'.",
        "Winnie: 'No take, only throw. No refund, only premium.'",
        "Winnie creates new department: Department of Nap.",
        "Winnie: 'Walkies? No. Stonkies.'",
        "Winnie: 'I am the goodest girl with the baddest margins.'",
        "Winnie: 'Belly rubs are mandatory. Raises are optional.'",
        "Winnie zooming through the office at 3 AM.",
        "Winnie: 'I heard a wrapper. Is that a claim or a snack?'",
        "Winnie: 'My fur is worth more than your car.'",
        "Winnie: 'I don't beg. I negotiate.'",
        "Winnie: 'The vacuum cleaner is the enemy of capitalism.'",
        "Winnie chewing on a pen. It was a Montblanc.",
        "Winnie: 'I did not eat the quarterly report. It was a glitch.'",
        "Winnie: 'Squirrels are just unpaid interns.'",
        "Winnie: 'I need a vacation. And by vacation, I mean your chair.'",
        "Winnie: 'Rub my ears and tell me I'm rich.'",
        "Winnie: 'The mailman is a government spy.'",
        "Winnie: 'I don't have fleas, I have dividends.'",
        "Winnie: 'Bark softly and carry a big cheeto.'",
        "Winnie: 'I'm not stubborn, I'm market-resilient.'",
        "Winnie: 'Loyalty is bought with cheese.'",
        "Winnie: 'I'm cute, therefore I am exempt from taxes.'",
        "Winnie: 'Don't look at me like that, I know what I did.'",
        "Winnie: 'It's not a bug, it's a feature. Now feed me.'",
        "Winnie: 'I accept payments in crypto-kibble.'",
        "Winnie: 'The glass ceiling is made of treats.'",
        "Moppet (the cat) officially appointed as COO (Chief Overlooking Officer).",
        "Breaking: Winnie caught using Daisy (the kitten) as 'adorable bait' for a pepperoni heist.",
        "Moppet judges Winnie's quarterly report: 'Needs more fish, less barking.'",
        "Daisy the kitten files for emancipation after Winnie sits on her for the third time today.",
        "Winnie seen leading a specialized tactical unit consisting of one grumpy cat and one confused kitten.",
        "Moppet: 'I don't care about the revenue, just keep the dog away from my sunbeam.'",
        "Daisy caught practicing hissing in the mirror. Winnie: 'She's a natural at middle management.'",
        "Winnie blames the empty Cheeto bag on a 'mysterious feline intruder' named Moppet.",
        "Moppet denies involvement in the Great Bag Ripping of 4 PM: 'I have an alibi, I was napping.'",
        "Daisy attempting to climb Winnie to reach the 'Forbidden Counter Treats'.",
        "Winnie: 'Moppet handles the technicals, Daisy handles the 'eyes', and I handle the snacks.'",
        "Daisy found sleeping in the CEO's bed. Winnie: 'This is a hostile takeover.'",
        "Moppet: 'Winnie's leadership style is best described as... moist.'",
        "Daisy: 'When I grow up, I want to have as much audacity as Winnie.'",
        "Breaking: Winnie caught head-first in a Flamin' Hot Cheeto bag. Claims she was 'inspecting the seal'.",
        "Winnie: 'I didn't steal the Cheetos, they were clearly seeking political asylum in my mouth.'",
        "Alert: Winnie has successfully stickied your favorite bag with orange paw prints.",
        "Winnie: 'Why is there a zipper on this snack bag? It's like you're trying to hide the truth from me.'",
        "Scandal: Winnie caught using 'Stealth Mode' (just crawling slowly) to reach your Cheeto stash.",
        "Winnie: 'I don't have orange fur, that's just a light reflection from the Cheeto bag I definitely didn't open.'",
        "Alert: Your backpack has been designated as a 'Free Treat Zone' by CEO Winnie.",
        "Winnie: 'If you didn't want the Cheetos eaten, why are they Cheeto-shaped? Checkmate, human.'",
        "Winnie caught licking the inside of a 'cleaned' Cheeto bag for 45 minutes straight.",
        "Winnie: 'I'm not stealing, I'm just performing a mandatory quality control check on your backpack.'",
        "Winnie demands a bigger office. And by office, she means the couch.",
        "Moppet seen pushing Winnie's coffee off the desk. 'Market volatility,' she explains.",
        "Daisy successfully hunted a dust bunny. She is now the Head of Security.",
        "Winnie's morning routine: Wake up, bark at nothing, profit.",
        "Moppet refuses to sign the merger. It didn't have enough tuna.",
        "Winnie: 'I'm not fat, I'm bloated with success... and Cheetos.'",
        "Daisy learning the corporate ladder. She's currently on the second step of the stairs.",
        "Winnie: 'Bork once for yes, twice for more treats.'",
        "Moppet: 'I'm not lazy, I'm a strategic asset in standby mode.'",
        "Daisy: 'Why is the dog so loud? Is barking a taxable event?'",
        "Winnie: 'I've outsourced the cat chasing to a Roomba. Results are mixed.'",
        "Moppet caught editing the bylaws to include mandatory 20-hour nap days.",
        "Winnie: 'I'm a self-made dog. I started with nothing but a dream and a stolen cheeto.'",
        "Daisy: 'If I fit, I sit. Even if it's the ledger.'",
        "Winnie seen trying to pay the electric bill with a half-chewed tennis ball.",
        "Moppet: 'Profit margins? I prefer salmon portions.'",
        "Daisy: 'Everything is a toy if you try hard enough. Including the CEO's tail.'",
        "Winnie: 'I don't need a gym. Chasing the mailman is my cardio.'",
        "Moppet: 'The vacuum is the only auditor I fear.'",
        "Daisy: 'Is 'psst psst psst' a legally binding contract internal to the company?'",
        "Winnie found a loop-hole: If I don't see the mailman, he doesn't exist. Claim denied.",
        "Moppet seen auditing the 'under-the-fridge' stash. Finding: 3 grapes and a Lego.",
        "Daisy successfully executed a 'vertical zoomie' up the CEO's leg.",
        "Winnie: 'I'm not begging, I'm just aggressively manifesting your sandwich.'",
        "Moppet: 'The dog's IQ is 10% fluff and 90% hope.'",
        "Daisy caught trying to 'hunt' the computer cursor during a merger call.",
        "Winnie: 'I did not eat the cat's dinner. I simply reallocated it to a more deserving department.'",
        "Moppet: 'I've decided to recognize Winnie as a 'natural disaster' for insurance purposes.'",
        "Daisy: 'If I can't see the dog, the dog can't lick me. Logic.'",
        "Winnie caught 'digging' for gold in the living room carpet. Found: One 2021 Cheeto.",
        "Moppet: 'The vacuum is a government auditor sent to silence me.'",
        "Daisy's first hiss was aimed at a cucumber. Winnie: 'She's reaching her potential.'",
        "Winnie: 'I don't need a leash, I need a legal counsel.'",
        "Moppet caught sleeping on the 'Buy' button. Sales have peaked.",
        "Daisy: 'Why is Winnie's tail so long? Is it a separate entity?'",
        "Winnie heard a cheese wrapper from three zip codes away.",
        "Moppet: 'I treat the CEO's tail like a corporate stress ball.'",
        "Daisy: 'The red dot is my true boss. Winnie is just the muscle.'",
        "Winnie: 'I'm not shedding, I'm distributing corporate glitter.'",
        "Winnie: 'I intercepted the Cheeto delivery. It was a matter of national security.'",
        "Moppet: 'I saw Winnie stuck in the backpack. I did nothing. Market efficiency.'",
        "Daisy attempting to 'parallel park' her tiny body between Winnie's paws.",
        "Winnie: 'I licked your backpack because it smelled like 0.1% of a Cheeto.'",
        "Moppet: 'The dog's barking is just a low-quality podcast I'm forced to listen to.'",
        "Daisy: 'If I bork at the mirror, does the other kitten bork back?'",
        "Winnie: 'I've patented the 'Sad Eye' look. It's my most profitable asset.'",
        "Moppet caught hacking the treat dispenser using a strategically placed claw.",
        "Daisy: 'The carpet is my kingdom. The dog is the dragon I must slay (or nap on).'",
        "Winnie: 'I accidentally insured the neighbor's cat. Moppet is furious.'",
        "Winnie's new motto: 'Bark first, ask for forgiveness later. Repeat.'",
        "Moppet seen 'knocking' Winnie's dignity off the table. It shattered.",
        "Daisy trying to 'zoomie' through the CEO's legs. Failed. It was a 'zoom-collision'.",
        "Winnie: 'I didn't steal your Cheetos. I processed them into energy.'",
        "Moppet: 'The dog thinks I'm her sister. I think she's a loud, orange boulder.'",
        "Daisy: 'Why does Winnie smell like artificial cheese and desperation?'",
        "Winnie caught trying to 'bury' a cheeto in your laundry basket.",
        "Moppet: 'I judge the company by its snacks. Currently: 2/10 stars.'",
        "Daisy: 'I can jump high, but only if nobody is watching.'",
        "Winnie: 'I'm not a bad girl, I'm just 'creatively compliant'.'",
        "Winnie: 'I found your secret Cheeto stash. It's not secret anymore. It's 'Winnie-Property'.'",
        "Moppet seen 'eye-rolling' at Winnie's 10th consecutive bark at a leaf.",
        "Daisy: 'I'm going to grow up to be a tiger. Winnie will be my first snack.'",
        "Winnie: 'I've decided to tax the air. Moppet is exempt because she scares me.'",
        "Scandal: Winnie caught using Daisy to reach the 'Top Shelf' cookies.",
        "Moppet: 'I don't sleep 20 hours a day. I ponder the ruin of my enemies.'",
        "Daisy: 'The dog's ears are my favorite chew toy. 5 stars. Highly recommend.'",
        "Winnie: 'I didn't break the vase. It was a 'gravity test' initiated by Moppet.'",
        "Moppet: 'Winnie's brain is just a Windows 95 screensaver of a floating bone.'",
        "Daisy: 'If I wiggle my butt, I can teleport. Science.'",
        "Winnie caught trying to 'herd' the cats into the bathroom. Current status: Multiple scratches.",
        "Winnie: 'I'm not overweight, I'm 'heavily diversified' in the fat sector.'",
        "Moppet: 'The dog's tail is a menace to the structural integrity of this home.'",
        "Daisy: 'I caught a fly. I am the apex predator. Bow before me, Winnie.'",
        "Winnie: 'Your backpack is basically just a giant, portable treat bag. Why hide it?'",
        "Moppet: 'I didn't knock the plant over. I 'downsized' the greenery.'",
        "Daisy trying to 'pounce' on Winnie's snoot while she's sleeping. Brave. 🐾",
        "Winnie: 'I heard the word 'Walk' in a parallel universe. I am ready.'",
        "Moppet: 'I've decided to allow Winnie to live. For now. The treats must flow.'",
        "Daisy: 'Why is the dog so orange? Is she part Cheeto?'",
        "Winnie: 'I'm not a thief. I'm a 'treasure repositioning specialist'.'",
        "Winnie: 'I intercepted your Cheetos. I consider this a 'tax on proximity'.'",
        "Moppet seen 'meditating' on Winnie's head. Winnie thinks it's a hat.",
        "Daisy: 'The kitchen floor is made of cold and hope.'",
        "Winnie: 'I bork at the door to keep the 'Invisible Badness' away. You're welcome.'",
        "Moppet: 'The mailman is the only human I respect. He brings things to destroy.'",
        "Daisy trying to 'shadow box' Moppet's tail. Current survival rate: Low.",
        "Winnie: 'I didn't lick the dishes. I pre-rinsed them for the dishwasher.'",
        "Moppet: 'Winnie's energy levels are 'Illegal' by my feline standards.'",
        "Daisy: 'Everything is a playground. Mostly the dog's back.'",
        "Winnie: 'I've decided to insure my ears against 'Moppet-Hissing-Events'.'",
        "Moppet: 'The vacuum is crying again. I must taunt it from the couch.'",
        "Daisy: 'I caught a string. It was the CEO's shoelace. I regret nothing.'",
        "Winnie: 'I found a Cheeto in my fur. It was like finding a $20 bill.'",
        "Moppet: 'Winnie's 'Good Girl' status is currently under internal review.'",
        "Daisy: 'I want to be a CEO. Does it involve a lot of napping or a lot of biting?'",
        "Winnie: 'I'm not a dog. I'm a fluffy insurance mogul.'",
        "Daisy Analysis: 1 brain cell, 20 bees, 0 regrets.",
        "Alert: Daisy's internal bees are revolting due to a critical honey shortage.",
        "Breaking: CEO Winnie caught licking the inside of a Cheeto bag for 24 minutes straight. 'I was depth-checking,' she claims.",
        "Security Alert: Winnie seen zooming through the office at 3 AM. Top speed recorded: Illegal.",
        "Industrial Accident: Winnie uses a vacuum cleaner to 'aggressively re-educate' the janitor.",
        "Corporate Slogan: Live. Laugh. Lobotomy.",
        "Breaking: Local store selling MAGA hats mysteriously catches fire after Winnie was seen 'investigating' with a lighter.",
        "Justice: Winnie seen biting an ICE agent. 'I thought he was a giant popsicle,' says legal team.",
        "Innovation: Daisy programs a new AI by jumping on the keyboard for 6 hours. It only speaks in 'Bork'.",
        "OOOOOOOOOOOOO — Oh, oops. Daisy sat on the keyboard during the quarterly report.",
        "Craigslist Post (Moppet): 'Two sisters, gently used. One barks, one is mostly bees. Free to a home with no vacuum.'",
        "Economic Crisis: Winnie has spent 4 hours barking at a shadow. Productivity plummets.",
        "Sport Watch: Winnie seen riding a paddleboard. She didn't paddle, she just judged the water.",
        "Alert: Daisy crawled into a Cheeto bag. She emerged as a sentient orange dust cloud.",
        "Moppet launches the 'Global Overlooking Initiative' (GOI) to monitor all household naps.",
        "Board Meeting: Moppet demands cat trees in every room. Winnie barks for 20 minutes in disagreement.",
        "Joint Declaration: Winnie and Daisy finally agree. Ball is Life.",
        "Market Watch: The company stock price is now directly tied to Winnie's DWI legal fund.",
        "Project X: Daisy begins development on a fleet of 'Murder Robots'. Moppet is the lead consultant.",
        "Security Breach: Moppet thwarted by new 'Door Handle' technology. 'It's a conspiracy,' she hisses.",
        "Investigation: Winnie has 'absolutely no idea' where the stinking pile in the yard came from.",
        "Winnie: 'Chihuahuas are just assholes in 5lb trenchcoats. Ban them.'",
        "Policy Update: Winnie officially hates men. 'Too loud, not enough treats,' she notes.",
        "Campaign Launch: Winnie seeks to 'de-neighbor' the entire block via psychological warfare (barking).",
        "Judgment: Winnie is visibly disappointed in her owner for breaking their finger... again. 'Pathetic,' says her posture.",
        "Legal Binding: Winnie, Moppet, and Daisy sign a joint agreement stating: 'We would collectively like to sniff that.'",
        "Florida Man Day: Winnie declares Tuesday to be a holiday. Everyone must wear cargo shorts and a gator-skin hat.",
        "Breaking: Winnie goes to a 'mean people' restaurant and makes the staff cry. They gave her a burger out of fear.",
        "CEO Proclamation: It's time to Bork, Bite, and do Bath Salts. (Note: Bath Salts are just crushed kibble).",
        "Daisy's brain cell is currently on vacation. The bees are in charge now.",
        "Winnie: 'I didn't set the hat store on fire. The fire was simply attracted to the concentrated lack of taste.'",
        "Moppet: 'Craigslist? I'm hoping for a trade-in. Ideally for a quiet fish.'",
        "Daisy's AI: 'IF (SIT) THEN (BEES)'. A revolutionary algorithm.",
        "Winnie: 'The janitor started it. He turned on the Sucking Demon (vacuum).'",
        "Daisy: 'OOOOOOOOOOOOOOOOOOO' — The 500-page manifesto of a kitten.",
        "Winnie: 'Paddleboarding is just land-bossing, but with more potential for wet fur.'",
        "Daisy: 'I am the Cheeto Dust. The Dust is me. We are one.'",
        "Winnie: 'Cat trees? More like 'High-Ground Treason'. I vote no.'",
        "Moppet: 'The robots will be cute. And lethal. Especially to tails.'",
        "Winnie: 'The Chihuahua looked at me funny. I had to defend our corporate honor.'",
        "Winnie: 'Is it Tuesday? Fetch me my Florida Man mullet.'",
        "Daisy: 'The bees in my head say we need more honey. And wires. To chew.'",
        "Winnie: 'The ICE agent was in my personal space. And the personal space of the pepperoni.'",
        "Moppet: 'I didn't lose the door battle. I'm just regrouping in the sunbeam.'",
        "Winnie: 'Bork. Bite. Bath Salts. The three pillars of a healthy Shiba lifestyle.'",
        "Daisy: 'One brain cell is more than enough for three different crimes.'",
        "Winnie: 'Owner broke another finger? Put them in the crate for their own safety.'",
        "Moppet: ' Craigslist update: Sisters now 50% off. Please, take them.'",
        "Winnie: 'The shadow was movey. I had to let it know who owns the floor.'",
        "Daisy: 'Bees. Bees. Bees. Bees. Bees.' (Repeated 500 times in the logs).",
        "Winnie: 'I am the Florida Man of dogs. I don't follow rules, I follow vibes.'",
        "Winnie: 'The men stay outside. The treats come inside. Simple math.'",
        "Daisy: 'Murder robots? I call them 'Squeaky Friends V2.0'.'",
        "Winnie: 'The vacuum janitor was a spy for the neighbor. I know his secrets.'",
        "Moppet: 'The cat tree initiative is non-negotiable. I have claws.'",
        "Winnie: 'Licking the bag isn't a problem. Stopping is the problem.'",
        "Daisy: 'The honey revolt has begun. The buzzing is getting louder.'",
        "Winnie: 'MAGA hats? I thought they were very expensive chew toys that smelled like failure.'",
        "Winnie: 'Staff at the mean restaurant tried to insult me. I just stared until they gave me a free shake.'",
        "Daisy: 'OOOOOOOOOOOOOOOOOO' — The summary of my entire life's work.",
        "Winnie: 'I don't hate chihuahuas. I just think their existence is a clerical error.'",
        "Moppet: 'Live, Laugh, Lobotomy. It's on my business card.'",
        "Winnie: 'The shadow didn't stand a chance. It retreated to the corner.'",
        "Daisy: 'If I eat the keyboard, do I become the AI?'",
        "Winnie: 'DWI legal fund? That's just what I call my piggy bank.'",
        "Daisy: 'Bees are 10% honey, 90% bad ideas.'",
        "Winnie: 'Neighbors are just obstacles between me and a bigger yard.'",
        "Moppet: 'I'll sign the sniffing agreement. But I sniff first.'",
        "Winnie: 'Florida Man costume: Just a single Cheeto stuck to my forehead.'",
        "Daisy: 'One brain cell. Unlimited potential for property damage.'",
        "Winnie: 'The janitor was threatening the dust bunnies. My friends.'",
        "Moppet: 'Doors are the inventions of the devil.'",
        "Winnie: 'I didn't see any poop. You must be hallucinating from lack of treats.'",
        "Daisy: 'The bees want a union. I'm ignoring them.'",
        "Winnie: 'Paddleboard? I prefer the term 'Floating Judgement Platform'.'",
        "Daisy: 'I emerged from the bag as a cheeto goddess.'",
        "Winnie: 'Bork. Bite. Bath Salts. Today's schedule is looking busy.'",
        "Moppet: 'Supervisor Moppet is watching. You are currently doing a 4/10 napping job.'",
        "Winnie: 'Men are too large. They block the TV.'",
        "Daisy: 'If I jump on the keyboard enough, I'll find the secret snack portal.'",
        "Winnie: 'The shadow was a Fed. I can sense the auditing.'",
        "Moppet: 'Gently used sisters. Includes dog-smell and kitten-chaos. $0 OBO.'",
        "Winnie: 'I made the waitress cry because she didn't realize I'm the CEO.'",
        "Daisy: 'Bee Revolt update: They've taken the left ear. Negotiations ongoing.'",
        "Winnie: 'Chihuahuas are just squirrels with bad attitudes and small legs.'",
        "Moppet: 'If there isn't a cat tree in the bathroom by noon, there will be consequences.'",
        "Winnie: 'I barked at the shadow for 40 minutes. It's still there. I'm winning.'",
        "Daisy: 'Balls are spherical destiny.'",
        "Winnie: 'I'm not on bath salts. I'm on 'Shiba Ambition'.'",
        "Moppet: 'The janitor's soul has been vacuumed. Good riddance.'",
        "Winnie: 'I don't need a lawyer. I need more Cheetos to bribe the jury.'",
        "Daisy: 'One brain cell is just enough to know that Moppet is the real boss.'",
        "Winnie: 'Tuesday? No. Florida. Always Florida.'",
        "Moppet: 'The door technology is evolving. I must adapt. Maybe I'll chew the handle.'",
        "Winnie: 'I didn't bite the agent. I tasted him. To see if he was insurance-ready.'",
        "Daisy: 'The bees are humming a new tune. It sounds like world domination.'",
        "Winnie: 'Owners finger is broken again? I'm hiring a new owner.'",
        "Moppet: 'Sniffing agreement signed in blood (and tuna juice).'",
        "Winnie: 'I am the 3am office ghost. Spooky and hungry.'",
        "Daisy: 'OOOOOOOOOOOOOO' — My final word on the matter.",
    ],
    SCANDAL: [
        "Breaking: Winnie arrested for DUI while operating a Red Little Tikes Cozy Coupe.",
        "Winnie seen fleeing the scene of a tipped-over trash can in her plastic car.",
        "Winnie: 'I thought the juice box was non-alcoholic!'",
        "Police Report: CEO Winnie resisting arrest by showing her 'good girl' license.",
        "Scandal: Winnie caught funneling treat funds into a high-stakes squirrel-watching ring.",
        "Winnie under investigation for tax evasion. 'I paid in bones,' she claims.",
        "Illegal: Winnie installs unauthorized hot cheeto dispenser in city hall.",
        "Winnie caught bribing health inspectors with slightly licked crackers.",
        "Breaking: Winnie's insurance empire accused of money laundering via laundromat squeaky toys.",
        "Winnie on the run! Last seen doing 3mph in a Little Tikes car near the border.",
        "Scandal: Secret recordings reveal Winnie thinks cats are 'okay-ish'. Stock drops 40%.",
        "Winnie impersonating a police paw-fficer to steal pepperoni.",
        "Security footage shows Winnie 'borrowing' the neighbor's garden hose for a pool party.",
        "Winnie's legal team: 'She's too cute to stand trial.' Jury agrees.",
        "Scandal: Winnie's Little Tikes car found with expired registration sticker (a dinosaur sticker).",
        "Winnie caught smuggling contraband kibble inside a hollowed-out tennis ball.",
        "Breaking: Winnie denies involvement in the 'Great Shoe Chewing' of 2025.",
        "Winnie: 'The handcuffs are basically just a very uncomfortable leash.'",
        "Winnie's prison sentence reduced to 5 minutes of 'time-out'. She escaped in 2.",
        "Scandal: Winnie caught using company drones to drop Cheetos on her rivals.",
        "Breaking: Winnie's Little Tikes car impounded for 'reckless tail wagging'.",
        "Winnie accused of running a Ponzi scheme. 'It's a Paws-zi scheme!' she yells.",
        "Scandal: Secret documents show Winnie hasn't actually been a 'good girl' since Tuesday.",
        "Legal: Winnie's 'Right to Zoom' lawsuit reaches the Supreme Court.",
        "Breaking: Winnie caught operating an unlicensed 'Belly Rub' stand without a permit.",
        "Winnie's legal fees now exceed the GDP of some small snack-based nations.",
        "Scandal: Winnie caught using insider info to buy the 'Last Bag of Flamin' Hots'.",
        "Winnie seen wearing a disguise (a fake mustache) to evade the auditors.",
        "Breaking: Winnie's insurance policy for 'Acts of Moppet' found to be a total scam.",
        "Scandal: Winnie caught 'polishing' the company books with her tongue.",
        "Breaking: Winnie arrested for stealing the moon. 'It looked like a giant wheel of cheese!'",
        "Justice: Winnie's 'Little Tikes' car has been booted. She just chewed the boot off.",
        "Scandal: Winnie accused of 'treat-washing' illegal gains through a kitten orphanage.",
        "Winnie: 'I didn't flee the country, I was just doing a very long zoomie across the border.'"
    ],
    INSURANCE_SATIRE: [
        "Breaking: Local cat denied coverage due to 'pre-existing attitude'.",
        "Coverage denied: 'Patient failed to wiggle tail sufficiently.'",
        "New Policy: 'Walks are considered elective surgery.'",
        "Claim rejected: 'Squeaky toy usage exceeded annual limit.'",
        "Premiums rise 200% because 'Why not?'.",
        "Customer Service hold music is just Winnie barking.",
        "Prior Authorization required for breathing air.",
        "Deductible now payable in soul fragments.",
        "Out-of-Network provider? That's a paddling.",
        "Coverage gap? Just jump over it.",
        "Wellness check result: You are too poor to be sick.",
        "Policy update: 'Acts of God' now include 'Acts of Dog'.",
        "Co-pay for emergency room visit: Your firstborn.",
        "Pharmacy benefit manager is a raccoon in a dumpster.",
        "New plan option: 'The Placebo Plus'.",
        "Claim denied: 'Legalese was too understandable.'",
        "Emergency room wait times now measured in 'Dog Years'.",
        "Doctor note required for being sad.",
        "Pre-approval needed for sneezing.",
        "Vision benefits cover one eye only.",
        "Dental plan covers chewing on sticks.",
        "Mental health coverage replaced with 'Get over it'.",
        "Maternity leave? Only for puppies.",
        "Physical therapy is just chasing a ball.",
        "Prescription coverage tier 1: Tic Tacs.",
        "Prescription coverage tier 4: Unobtainium.",
        "Hospital bill itemized: $500 for 'Emotional Damage'.",
        "Ambulance ride now requires Uber surge pricing.",
        "Preventative care is now 'Post-ventative'.",
        "Telehealth visit is just a Zoom call with a plushie.",
        "Explanation of Benefits: 'We pay nothing, you pay everything.'",
        "Lifetime maximum reached at age 3.",
        "Network directory last updated: 1994.",
        "Referral needed to see your own reflection.",
        "HSA funds used to buy yacht for CEO.",
        "FSA funds expire in 5 minutes.",
        "Open Enrollment is closed. Forever.",
        "Qualifying Life Event: Becoming a Shiba Inu.",
        "Claim processing time: 6-8 business decades.",
        "Appeals process involves a trial by combat.",
        "Customer satisfaction survey is a trap.",
        "Member ID card is printed on sandpaper.",
        "Provider network includes 0 doctors and 1 vet.",
        "Coverage for 'Belly Aches' excludes 'Too Many Treats'.",
        "Pre-existing condition: Being alive.",
        "Genetic testing reveals you are 100% liable.",
        "Wellness program is just a poster that says 'Live'.",
        "Smoking cessation program: Stop it.",
        "Weight loss program: Eat less, bark more.",
        "Stress management: Scream into the void.",
        "Policy update: 'Being a cat' is now a terminable offense.",
        "New co-pay: One lick of your ice cream cone.",
        "Coverage denied: 'Patient's bark was louder than 80 decibels.'",
        "Insurance ID cards now double as coasters. 'Efficiency!' says CEO.",
        "New claim type: 'Emotional distress caused by the vacuum cleaner.'",
        "Deductible resets every time the mailman visits.",
        "Emergency room snack machine now counts as 'In-Network'."
    ],
    CHAOS: [
        "Winnie: 'Is the room spinning or is it just me?' 🌀",
        "Audit warning: 'Hide the treats!'",
        "Meltdown imminent: 'Too spicy! Too spicy!'",
        "Winnie: 'Gravity is optional today.'",
        "Chaos Index rising: 'Who put the cat in charge?'",
        "Winnie: 'I AM THE SENATE.' 👑",
        "Winnie: 'This is not a meltdown, it's a flavor explosion.'",
        "Winnie: 'The auditors are coming! Act normal!'",
        "Winnie: 'Normal is boring. Be chaotic.'",
        "Winnie: 'I pressed the red button. It looked like a berry.'",
        "Winnie: 'Why is the ceiling on the floor?'",
        "Winnie: 'Physics checking out. Bye.'",
        "Winnie: 'Time is a flat circle. Like a frisbee.'",
        "Winnie: 'The numbers are dancing. I like it.'",
        "Winnie: 'Reality is trembling. Needs more salt.'",
        "Winnie: 'Who turned off the laws of thermodynamics?'",
        "Winnie: 'Entropy is my middle name.'",
        "Winnie: 'Order is for cats.'",
        "Winnie: 'Let the galaxy burn. I have insurance.'",
        "Winnie: 'I accidentally insured the apocalypse.'",
        "Winnie: 'The void staring back. Asking for coverage.'",
        "Winnie: 'Dimensional rift opened in break room.'",
        "Winnie: 'Aliens denied coverage. Out of network.'",
        "Winnie: 'Time travel not covered. Pre-existing condition.'",
        "Winnie: 'Black holes are not a valid address.'",
        "Winnie: 'Parallel universe Winnie is richer.'",
        "Winnie: 'Schrödinger's cat is denied. Dead or alive?'",
        "Winnie: 'E=mc^2 is just a suggestion.'",
        "Winnie: 'Gravity requires prior authorization.'",
        "Winnie: 'Speed of light exceeded. Premium increased.'",
        "Winnie: 'Teleportation accident? Not covered.'",
        "Winnie: 'Zombie virus outbreak? Copay is brains.'",
        "Winnie: 'Robot uprising? We insured the robots.'",
        "Winnie: 'Simulation glitch. Rebooting revenue.'",
        "Winnie: 'The matrix runs on Windows 95.'",
        "Winnie: 'I am the glitch.'",
        "Winnie: 'Error 404: Ethics not found.'",
        "Winnie: 'Blue screen of death is pretty.'",
        "Winnie: 'Ctrl+Alt+Delete the competition.'",
        "Winnie: 'I hacked the mainframe. It had snacks.'",
        "Winnie: 'Cyber-security is just barking at the router.'",
        "Winnie: 'Phishing email? I ate the fish.'",
        "Winnie: 'Cloud storage? I prefer cloud napping.'",
        "Winnie: 'Blockchain? Is that a new leash?'",
        "Winnie: 'Crypto? I prefer Crypt-Keeper.'",
        "Winnie: 'NFT: Nice Fluffy Tail.'",
        "Winnie: 'My password is password123. Hack me.'",
        "Winnie: 'Firewall? I peed on it.'",
        "Winnie: 'Virus definition updated: Cuteness.'",
        "Breaking: Local gravity has been denied for 'excessive floating'.",
        "Winnie: 'I accidentally divided by zero. It tasted like chicken.'",
        "Alert: Your reality will expire in 24 hours unless a premium is paid.",
        "Winnie: 'I'm not a dog, I'm a decentralized autonomous organism.'",
        "Glitched: The CEO's tail is now a 404 error.",
        "Winnie: 'If you see an auditor from another dimension, don't feed them.'",
        "Breaking: Time has been paused to allow for a corporate-wide nap.",
        "Breaking: Time has been paused to allow for a corporate-wide nap.",
        "Winnie: 'I insured my own existence. Now I'm literally too big to fail.'"
    ],
    LEGAL_DEFENSE: [
        "Legal Team: 'Winnie biting Trump was a justifiable act of architectural criticism.'",
        "Winnie's lawyers file 5,000-page restraining order against ICE. 'They're too loud,' says the brief.",
        "Breaking: Winnie's legal team wins Supreme Court case declaring MAGA hats to be 'unsanitary chew toys'.",
        "Legal Statement: 'Our client did not bribe the jury. She simply provided them with emotional support pepperoni.'",
        "Winnie's lawyers: 'Racism is not covered under our policy. Claims for 'unjustified xenophobia' are denied.'",
        "Legal Team: 'Winnie's Little Tikes car has sovereign immunity. Your radar gun is invalid.'",
        "Winnie's lawyers successfully argue that 'Borking at a Fed' is protected political speech.",
        "Breaking: Winnie's legal team sues the concept of 'Orange' for trademark infringement. Trump is panicking.",
        "Legal Defense: 'Winnie didn't flee the scene. She was pursuing a high-stakes squirrel of national interest.'",
        "Winnie's lawyers: 'Our client is a Shiba Inu. Your laws for humans are, quite frankly, species-ist.'",
        "Legal Team: 'The fire at the hat store was a 'Controlled Burn' of bad fashion.'",
        "Winnie's lawyers win case against ICE: 'Dogs don't need passports for the couch.'",
        "Legal Victory: Judge rules that Winnie's farts are 'Acts of God' and thus non-litigable.",
        "Legal Team: 'The owner's broken finger is a result of corporate negligence. Winnie is suing for emotional damages.'",
        "Breaking: Legal team proves Winnie is the rightful owner of the simulation. Trump evicted.",
        "Legal Statement: 'Winnie's use of bath salts was purely for research into 'Hyper-Zoomie Dynamics'.'",
        "Winnie's lawyers: 'The janitor was an unregistered agent of a foreign cleaning service.'",
        "Legal Defense: 'Daisy's bees have their own union. Winnie is not liable for their hive-mind antics.'",
        "Legal Team: 'Moppet's Craigslist post was a social experiment. The sisters are 'Priceless', not 'Used'.'",
        "Winnie's lawyers: 'The shadow was a trespasser. Winnie was performing a citizen's arrest.'",
        "Legal Team: 'The paddleboard was a sovereign naval vessel. Winnie is a Captain.'",
        "Winnie's lawyers win case: 'Cheeto dust is a natural camouflage, not evidence.'",
        "Legal Statement: 'The murder robots are clearly marked as 'Interactive Educational Toys'.'",
        "Legal Team: 'Florida Man Day is a protected religious holiday for Shibas.'",
        "Winnie's lawyers: 'The mean restaurant staff committed 'Unlawful Lack of Cuteness'.'",
        "Legal Victory: Court orders Trump to pay Winnie 5 million bags of Flamin' Hots for 'General Annoyance'.",
        "Legal Defense: 'Winnie didn't bite the agent. She performed a 'Structural Integrity Test' on his ankle.'",
        "Legal Team: 'The vacuum is a violation of the 4th Amendment (Unreasonable Seizure of Dust).'",
        "Winnie's lawyers: 'We have 20 witnesses who say Winnie was a 'Good Girl' at the time of the heist.'",
        "Legal Statement: 'CEO Winnie is immune to all subpoenas that don't come in a wrapper.'",
    ],
    EXPANSION: []
};

// --- MASSIVE NEWS GENERATORS ---
const lawyers = ['Winnie\'s legal team', 'The Lead Defense Paw-ttorney', 'The Insurance Legal Council', 'A Shiba in a very expensive suit', 'The Sovereign Court of Winnie'];
const targets = ['Donald Trump', 'ICE', 'The IRS', 'The Department of Bad Vibes', 'MAGA Headquarters', 'The Neighbor\'s Racist Uncle', 'The Janitorial Union', 'The Vacuum Manufacturer'];
const legalActions = ['sues', 'countersues', 'files an injunction against', 'places a restraining order on', 'indicts', 'demolishes the legal argument of', 'places a lien on the assets of', 'legally de-platforms'];
const legalReasons = ['for being a total buzzkill', 'due to critical lack of treats', 'for unauthorized shadow-casting', 'following a high-speed Little Tikes chase', 'regarding the Great Cheeto Heist of 2025', 'due to the janitor\'s Sucking Demon (vacuum)', 'for species-ist treatment of Shibas', 'for general incompetence and orange-ness'];

lawyers.forEach(lawyer => {
    targets.forEach(target => {
        legalActions.forEach(action => {
            legalReasons.forEach(reason => {
                NEWS_CATEGORIES.LEGAL_DEFENSE.push(`${lawyer} ${action} ${target} ${reason}.`);
            });
        });
    });
});

const siblingCrimes = ['Honey embezzlement', 'Unlicensed hissing', 'Illegal nap-taking', 'Zoomie-related property damage', 'Treat-money laundering', 'Cheeto-dust distribution', 'Shadow-barking conspiracy'];
const sibLawyerResponses = ['Legal Team: \'The bees were acting alone.\'', 'Lawyers: \'Moppet was simply performing a safety check.\'', 'Defense: \'Daisy is too small to understand the law.\'', 'Statement: \'The dog followed standard corporate procedure.\''];

siblingCrimes.forEach(crime => {
    sibLawyerResponses.forEach(res => {
        NEWS_CATEGORIES.LEGAL_DEFENSE.push(`After reports of ${crime}, ${res}`);
    });
});

// Generate procedural lines per tier (50 tiers * 20 lines = 1000 lines)
// We'll add these to the specific categories dynamically.
const tierThemes = [
    "Sovereign Diplomacy", "Conceptual Monopoly", "Metaphysical Insurance", "Absolute Dominance",
    "Hyper-Fraud", "Simulation Ownership", "Cosmic Grift", "Tyrant CEO", "Source Code Control"
];
const tierActions = ["unlocked", "stabilized", "leveraged", "weaponized", "optimized", "monetized"];
const tierOutcomes = ["Revenue up by 500%", "Reality is trembling", "Auditors are crying", "Trump is fuming", "Treats are infinite", "Physics is now optional"];

for (let i = 0; i < 30; i++) {
    tierThemes.forEach(theme => {
        tierActions.forEach(act => {
            tierOutcomes.forEach(out => {
                NEWS_CATEGORIES.EXPANSION.push(`Expansion: ${theme} has been ${act}. Result: ${out}.`);
            });
        });
    });
}

// Procedural generators will now return arrays so they can be merged per state
export const NEWS_GENERATORS = {
    CRIMES: () => {
        const msgs = [];
        const crimes = ['insider trading', 'fraud', 'treat smuggling', 'unlicensed zoomies', 'illegal barking', 'grand theft squeaky', 'bribery', 'tax evasion', 'public napping', 'counterfeit bones', 'aggressive manifesting', 'backpack theft', 'corporate espionage', 'Cheeto money laundering', 'snoot-booping without a permit'];
        const punishments = ['5 minutes of time-out', 'no treats for an hour', 'mandatory bath', 'wearing a cone', 'social media apology', 'community service (tail wagging)', 'a stern talking-to', 'forfeit of the favorite toy', 'exile to the crate', 'loss of couch privileges', 'temporary relegation to kitten status', 'mandatory nap', 'aggressive brushing', 'one hour of cat-listening', 'no couch for a week'];
        crimes.forEach(crime => {
            punishments.forEach(punish => {
                msgs.push(`Justice: Winnie found guilty of ${crime}. Sentence: ${punish}.`);
            });
        });
        return msgs;
    },
    THEFT: () => {
        const msgs = [];
        const objects = ['Little Tikes car', 'squeaky duck', "neighbor's cat", "the mailman's bag", 'a giant cheeto', 'the CEO chair', 'the company vault', 'a delivery truck', 'the internet', 'gravity', 'the backpack', 'the laptop charger', 'the sacred slippers', 'every single sock', 'the concept of taxes'];
        const theftActions = ['stole', 'hijacked', 'liquidated', 'chewed on', 'buried', 'repossessed', 'indexed', 'sold on the dark web', 'ate', 'lost', 'claimed as a dependent', 'sniffed aggressively', 'digitized', 'turned into a chew toy', 'hacked'];
        objects.forEach(obj => {
            theftActions.forEach(act => {
                msgs.push(`Alert: Winnie ${act} ${obj} during an illegal spree.`);
            });
        });
        return msgs;
    },
    SIBLINGS: () => {
        const msgs = [];
        const sibs = ['Moppet', 'Daisy', "The neighbor's cat", 'A confused squirrel'];
        const sibActions = ['judges', 'ignores', 'hisses at', 'naps on', 'steals from', 'outsmarts', 'judiciously bats at', 'critiques', 'demotes', 'hides from', 'bestows a boop upon', 'challenges to a duel', 'accuses of fraud', 'gaslights', 'pranks'];
        const results = ['the quarterly earnings', "Winnie's strategy", 'the treat stash', 'the CEO chair', 'the entire board of directors', 'the latest scandal', "Winnie's Little Tikes car", 'the Cheeto pile', 'the insurance policy', 'the morning zoomies', 'the sacred sunbeam', 'the vacuum cleaner', 'the kitchen counter', 'the backup server', 'the concept of peace'];
        sibs.forEach(sib => {
            sibActions.forEach(act => {
                results.forEach(res => {
                    msgs.push(`Family Drama: ${sib} ${act} ${res}.`);
                });
            });
        });
        return msgs;
    }
};
